namespace NoobOfLegends.APIs.RiotApi
{
    /// <summary>
    /// An enum representing the different queue types offered by the riot api.
    /// </summary>
    public enum RiotQueue
    {
        None = -1,
        CustomGame = 0,
        HowlingAbyss1v1Showdown = 72,
        HowlingAbyss2v2Showdown = 73,
        SummonersRift6v6Hexakill = 75,
        SummonersRiftUltraRapidFire = 76,
        HowlingAbyssOneForAll = 78,
        SummonersRiftUltraRapidFireCoop = 83,
        TwistedTreeline6v6Hexakill = 98,
        ButchersBridge5v5AllRandomAllMid = 100,
        SummonersRiftNemesis = 310,
        SummonersRiftBlackMarketBrawlers = 313,
        CrystalScarDefinitelyNotDominion = 317,
        SummonersRiftAllRandom = 325,
        SummonersRift5v5Draft = 400,
        SummonersRift5v5RankedSolo = 420,
        SummonersRift5v5BlindPick = 430,
        SummonersRift5v5RankedFlex = 440,
        HowlingAbyss5v5AllRandomAllMid = 450,
        SummonersRiftBloodHuntAssassin = 600,
        CosmicRuinsDarkStarSingularity = 610,
        SummonersRiftClashGames = 700,
        TwistedTreelineCoopVsBeginnerBots = 820,
        SummonersRiftCoopVsIntroBots = 830,
        SummonersRiftCoopVsBeginnerBots = 840,
        SummonersRiftCoopVsIntermediateBots = 850,
        SummonersRiftAllRandomUltraRapidFire = 900,
        CrystalScarAscension = 910,
        HowlingAbyssLegendOfThePoroKing = 920,
        SummonersRiftNexusSiege = 940,
        SummonersRiftDoomBotsVoting = 950,
        SummonersRiftDoomBotsStandard = 960,
        ValoranCityParkStarGuardiansInvasionNormal = 980,
        ValoranCityParkStarGuardiansInvasionOnslaught = 990,
        OverchargeProjectHunters = 1000,
        SummonersRiftSnowAllRandomUltraRapidFire = 1010,
        SummonersRiftOneForAll = 1020,
        CrashSiteOdysseyExtractionIntro = 1030,
        CrashSiteOdysseyExtractionCadet = 1040,
        CrashSiteOdysseyExtractionCrewMember = 1050,
        CrashSiteOdysseyExtractionCaptain = 1060,
        CrashSiteOdysseyExtractionOnslaught = 1070,
        NexusBlitz = 1300,
        SummonersRiftUltimateSpellbook = 1400,
        SummonersRiftPickUltraRapidFire = 1900,
        SummonersRiftTutorial1 = 2000,
        SummonersRiftTutorial2 = 2010,
        SummonersRiftTutorial3 = 2020,
    }
}
